// ============================================================
// VULOTA DASHBOARD — Static / Dummy Data
// ============================================================

export const statsCards = [
  {
    id: 1,
    title: "Total Threats Detected",
    value: "2,847",
    change: "+12.5%",
    trend: "up",
    icon: "shield-alert",
    color: "red",
    description: "vs last month",
  },
  {
    id: 2,
    title: "Active Users",
    value: "1,293",
    change: "+8.2%",
    trend: "up",
    icon: "users",
    color: "blue",
    description: "vs last month",
  },
  {
    id: 3,
    title: "Vulnerabilities Patched",
    value: "486",
    change: "+23.1%",
    trend: "up",
    icon: "check-shield",
    color: "green",
    description: "vs last month",
  },
  {
    id: 4,
    title: "Pending Incidents",
    value: "34",
    change: "-5.4%",
    trend: "down",
    icon: "alert-triangle",
    color: "orange",
    description: "vs last month",
  },
];

export const trafficData = [
  { name: "Jan", traffic: 4200, attacks: 240, blocked: 180 },
  { name: "Feb", traffic: 3800, attacks: 198, blocked: 160 },
  { name: "Mar", traffic: 5100, attacks: 320, blocked: 290 },
  { name: "Apr", traffic: 4700, attacks: 280, blocked: 250 },
  { name: "May", traffic: 6200, attacks: 410, blocked: 380 },
  { name: "Jun", traffic: 5800, attacks: 360, blocked: 330 },
  { name: "Jul", traffic: 7100, attacks: 490, blocked: 460 },
  { name: "Aug", traffic: 6500, attacks: 420, blocked: 395 },
  { name: "Sep", traffic: 7800, attacks: 530, blocked: 510 },
  { name: "Oct", traffic: 8200, attacks: 580, blocked: 555 },
  { name: "Nov", traffic: 7600, attacks: 510, blocked: 490 },
  { name: "Dec", traffic: 9100, attacks: 640, blocked: 620 },
];

export const threatDistribution = [
  { name: "Malware", value: 35, color: "#ef4444" },
  { name: "Phishing", value: 25, color: "#f59e0b" },
  { name: "DDoS", value: 18, color: "#8b5cf6" },
  { name: "SQL Injection", value: 12, color: "#4f8ef7" },
  { name: "XSS", value: 10, color: "#10b981" },
];

export const weeklyActivity = [
  { day: "Mon", scans: 120, incidents: 8, resolved: 6 },
  { day: "Tue", scans: 145, incidents: 12, resolved: 10 },
  { day: "Wed", scans: 98, incidents: 5, resolved: 5 },
  { day: "Thu", scans: 167, incidents: 15, resolved: 12 },
  { day: "Fri", scans: 189, incidents: 18, resolved: 14 },
  { day: "Sat", scans: 76, incidents: 4, resolved: 4 },
  { day: "Sun", scans: 54, incidents: 2, resolved: 2 },
];

export const users = [
  {
    id: 1,
    name: "Alex Johnson",
    email: "alex.johnson@vulota.io",
    role: "Admin",
    status: "Active",
    lastLogin: "2 min ago",
    threats: 0,
    avatar: "AJ",
    avatarColor: "#4f8ef7",
    location: "New York, US",
    joined: "Jan 12, 2024",
  },
  {
    id: 2,
    name: "Sarah Chen",
    email: "sarah.chen@vulota.io",
    role: "Analyst",
    status: "Active",
    lastLogin: "15 min ago",
    threats: 2,
    avatar: "SC",
    avatarColor: "#8b5cf6",
    location: "San Francisco, US",
    joined: "Mar 5, 2024",
  },
  {
    id: 3,
    name: "Marcus Williams",
    email: "m.williams@vulota.io",
    role: "Security Engineer",
    status: "Active",
    lastLogin: "1 hr ago",
    threats: 0,
    avatar: "MW",
    avatarColor: "#10b981",
    location: "London, UK",
    joined: "Feb 18, 2024",
  },
  {
    id: 4,
    name: "Priya Patel",
    email: "priya.patel@vulota.io",
    role: "Analyst",
    status: "Inactive",
    lastLogin: "3 days ago",
    threats: 1,
    avatar: "PP",
    avatarColor: "#f59e0b",
    location: "Mumbai, IN",
    joined: "Apr 22, 2024",
  },
  {
    id: 5,
    name: "David Kim",
    email: "d.kim@vulota.io",
    role: "Viewer",
    status: "Active",
    lastLogin: "30 min ago",
    threats: 0,
    avatar: "DK",
    avatarColor: "#06b6d4",
    location: "Seoul, KR",
    joined: "May 10, 2024",
  },
  {
    id: 6,
    name: "Emma Rodriguez",
    email: "e.rodriguez@vulota.io",
    role: "Security Engineer",
    status: "Suspended",
    lastLogin: "2 weeks ago",
    threats: 5,
    avatar: "ER",
    avatarColor: "#ef4444",
    location: "Madrid, ES",
    joined: "Jun 1, 2024",
  },
  {
    id: 7,
    name: "James O'Brien",
    email: "j.obrien@vulota.io",
    role: "Admin",
    status: "Active",
    lastLogin: "5 min ago",
    threats: 0,
    avatar: "JO",
    avatarColor: "#4f8ef7",
    location: "Dublin, IE",
    joined: "Jan 30, 2024",
  },
  {
    id: 8,
    name: "Yuki Tanaka",
    email: "y.tanaka@vulota.io",
    role: "Analyst",
    status: "Active",
    lastLogin: "2 hr ago",
    threats: 0,
    avatar: "YT",
    avatarColor: "#8b5cf6",
    location: "Tokyo, JP",
    joined: "Jul 14, 2024",
  },
];

export const activityLogs = [
  {
    id: 1,
    type: "threat",
    severity: "critical",
    message: "Critical malware detected on endpoint EP-0042",
    user: "System",
    time: "2 min ago",
    ip: "192.168.1.42",
    icon: "shield-alert",
  },
  {
    id: 2,
    type: "auth",
    severity: "warning",
    message: "Multiple failed login attempts from IP 203.0.113.45",
    user: "Auth Service",
    time: "8 min ago",
    ip: "203.0.113.45",
    icon: "lock",
  },
  {
    id: 3,
    type: "scan",
    severity: "info",
    message: "Scheduled vulnerability scan completed — 3 new CVEs found",
    user: "Scanner Bot",
    time: "25 min ago",
    ip: "10.0.0.1",
    icon: "search",
  },
  {
    id: 4,
    type: "user",
    severity: "info",
    message: "User Sarah Chen updated firewall rules",
    user: "Sarah Chen",
    time: "1 hr ago",
    ip: "10.0.0.15",
    icon: "user",
  },
  {
    id: 5,
    type: "patch",
    severity: "success",
    message: "Security patch CVE-2024-1234 applied successfully",
    user: "Patch Manager",
    time: "2 hr ago",
    ip: "10.0.0.1",
    icon: "check-circle",
  },
  {
    id: 6,
    type: "threat",
    severity: "high",
    message: "SQL injection attempt blocked on /api/users endpoint",
    user: "WAF",
    time: "3 hr ago",
    ip: "198.51.100.22",
    icon: "zap",
  },
  {
    id: 7,
    type: "auth",
    severity: "info",
    message: "Admin Alex Johnson logged in from new device",
    user: "Alex Johnson",
    time: "4 hr ago",
    ip: "172.16.0.5",
    icon: "log-in",
  },
  {
    id: 8,
    type: "scan",
    severity: "warning",
    message: "Port scan detected from external IP 45.33.32.156",
    user: "IDS",
    time: "5 hr ago",
    ip: "45.33.32.156",
    icon: "radar",
  },
  {
    id: 9,
    type: "patch",
    severity: "success",
    message: "SSL certificate renewed for vulota.io",
    user: "Cert Manager",
    time: "6 hr ago",
    ip: "10.0.0.1",
    icon: "award",
  },
  {
    id: 10,
    type: "threat",
    severity: "medium",
    message: "Suspicious outbound traffic detected from EP-0018",
    user: "System",
    time: "8 hr ago",
    ip: "192.168.1.18",
    icon: "activity",
  },
];

export const securityInsights = [
  {
    id: 1,
    title: "CVE-2024-3094",
    severity: "Critical",
    cvss: 9.8,
    affected: "XZ Utils 5.6.0-5.6.1",
    status: "Patched",
    discovered: "Mar 29, 2024",
    description: "Supply chain backdoor in XZ Utils compression library",
  },
  {
    id: 2,
    title: "CVE-2024-21762",
    severity: "Critical",
    cvss: 9.6,
    affected: "Fortinet FortiOS",
    status: "Monitoring",
    discovered: "Feb 8, 2024",
    description: "Out-of-bounds write vulnerability in SSL VPN",
  },
  {
    id: 3,
    title: "CVE-2024-1709",
    severity: "High",
    cvss: 8.8,
    affected: "ConnectWise ScreenConnect",
    status: "Patched",
    discovered: "Feb 19, 2024",
    description: "Authentication bypass vulnerability",
  },
  {
    id: 4,
    title: "CVE-2024-27198",
    severity: "High",
    cvss: 8.3,
    affected: "JetBrains TeamCity",
    status: "In Progress",
    discovered: "Mar 4, 2024",
    description: "Authentication bypass in web server component",
  },
  {
    id: 5,
    title: "CVE-2024-4577",
    severity: "High",
    cvss: 7.8,
    affected: "PHP 8.x (Windows)",
    status: "Patched",
    discovered: "Jun 6, 2024",
    description: "Argument injection vulnerability in CGI mode",
  },
  {
    id: 6,
    title: "CVE-2024-38112",
    severity: "Medium",
    cvss: 7.5,
    affected: "Windows MSHTML",
    status: "Monitoring",
    discovered: "Jul 9, 2024",
    description: "Spoofing vulnerability via MHTML protocol handler",
  },
];

export const systemHealth = [
  { name: "Firewall", status: "Operational", uptime: "99.98%", load: 23 },
  { name: "IDS/IPS", status: "Operational", uptime: "99.95%", load: 45 },
  { name: "SIEM", status: "Degraded", uptime: "97.20%", load: 78 },
  { name: "Endpoint Protection", status: "Operational", uptime: "99.99%", load: 31 },
  { name: "Vulnerability Scanner", status: "Operational", uptime: "99.80%", load: 12 },
  { name: "Threat Intelligence", status: "Operational", uptime: "99.90%", load: 56 },
];

export const recentReports = [
  {
    id: 1,
    title: "Monthly Security Assessment — October 2024",
    type: "Assessment",
    generated: "Nov 1, 2024",
    size: "2.4 MB",
    status: "Ready",
  },
  {
    id: 2,
    title: "Penetration Test Report — Q3 2024",
    type: "Pentest",
    generated: "Oct 15, 2024",
    size: "5.1 MB",
    status: "Ready",
  },
  {
    id: 3,
    title: "Vulnerability Scan — Weekly #44",
    type: "Scan",
    generated: "Oct 31, 2024",
    size: "1.2 MB",
    status: "Ready",
  },
  {
    id: 4,
    title: "Incident Response Report — IR-2024-089",
    type: "Incident",
    generated: "Oct 28, 2024",
    size: "890 KB",
    status: "Ready",
  },
  {
    id: 5,
    title: "Compliance Audit — ISO 27001",
    type: "Compliance",
    generated: "Generating...",
    size: "—",
    status: "Processing",
  },
];
